### ISSUE TITLE
[cmd] error in communities fastgreedy command

### ISSUE THREAD

**Issue by lorenbioinfo** [mazzalab/pyntacle#50]
Case study 2 notebook

command used :`pyntacle communities fastgreedy -i APID_CAEEL_Level2_maincomponent.adjm -d ./CAEEL_communities -o CAEEL_Interactome --min-nodes 40 --plot-format png`

error received:
```
usage: pyntacle communities fastgreedy [-h] [-f] [-N] [-d] [-M] [-m] [-C] [-c] [-L] [--input-separator] [--save-binary] [-o] [-u] [--no-output-header] [--output-separator] --input-file [FILE] [--weights FILE] [--weights-format] [--clusters]
pyntacle communities {fastgreedy, infomap, leading-eigenvector, community-walktrap} [arguments] fastgreedy: error: argument : invalid choice: 'png' (choose from 'fastgreedy', 'infomap', 'leading-eigenvect
```

**Comment by mazzalab** [comment]
the option --plot-format was removed since version 1.1 and after the introduction of **PyntacleInk**. The correct command is:

`pyntacle communities fastgreedy -i APID_CAEEL_Level2_maincomponent.adjm -d ./CAEEL_communities -o CAEEL_Interactome --min-nodes 40` <s>--plot-format png</s>

please correct, thanks
